export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const SET_CATEGORIES_FILTER_PROPERTY = 'SET_CATEGORIES_FILTER_PROPERTY';
