export const WELCOME_SKIPPED = 'WELCOME_SKIPPED';
export const PRODUCTS_VIEW_TYPE_CHANGED = 'PRODUCTS_VIEW_TYPE_CHANGED';
export const SET_SINGLE_PRODUCT_SCROLLING = 'SET_SINGLE_PRODUCT_SCROLLING';
export const REDIRECT_TO_ODER_AFTER_LOGIN = 'REDIRECT_TO_ODER_AFTER_LOGIN';
export const SET_FETCH_CATEGORIES_LOADING = 'SET_FETCH_CATEGORIES_LOADING';
export const SET_COLLECTION_LOADING = 'SET_COLLECTION_LOADING';
export const SET_SEARCH_PRODUCTS_ERROR = 'SET_SEARCH_PRODUCTS_ERROR';
