export const WELCOME_SKIPPED = 'WELCOME_SKIPPED';
export const PRODUCTS_VIEW_TYPE_CHANGED = 'PRODUCTS_VIEW_TYPE_CHANGED';
export const SET_SINGLE_PRODUCT_SCROLLING = 'SET_SINGLE_PRODUCT_SCROLLING';
export const REDIRECT_TO_ODER_AFTER_LOGIN = 'REDIRECT_TO_ODER_AFTER_LOGIN';
