export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SET_PRODUCTS_FILTER_PROP = 'SET_PRODUCTS_FILTER_PROP';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const MODIFY_PRODUCT = 'MODIFY_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
